AWSTemplateFormatVersion: 2010-09-09
Description: "This CloudFormation Template creates a private S3 Bucket"
Parameters:
  S3BucketName:
    Type: "String"
    Default: "<desired-bucket-name"
    Description: Name of the bucket to be created
  ProjectTag:
    Description: Name Of the project
    Type: String
    Default: "<value>"
  OwnerTag:
    Description: Name Of the Project Owner
    Type: String
    Default: "<value>"
  EnvTag:
    Description: Name Of the Env of the Resource
    Type: String
    Default: "<value>"
  ApplicationTag:
    Description: Name Of the Env of the Resource
    Type: String
    Default: "<value>"    
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref 'S3BucketName'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False      
      Tags:
        - Key: Name
          Value: !Ref 'S3BucketName'
        - Key: <value>
          Value: !Ref 'OwnerTag'
        - Key: <value>
          Value: !Ref 'ProjectTag'
        - Key: <value>
          Value: !Ref 'EnvTag'
        - Key: <value>
          Value: !Ref 'ApplicationTag'      
        - Key: <value>
          Value: ""
        - Key: <value>
          Value: ""
