AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a public S3 Bucket
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: <value>
      AccessControl: Private
      Tags:
        - Key: Name
          Value: <value>
        - Key: Owner
          Value: <value>
        - Key: <value>
          Value: <value>
        - Key: <value>
          Value: <value>
        - Key: <value>
          Value: <value>                 
Outputs:
  BucketName:
    Description: s3 bucket
    Value: !Ref s3Bucket
    Export: 
      Name: !Sub "${AWS::StackName}-BucketName" 
